# Generated by Django 4.2.13 on 2024-06-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='is_company',
            field=models.BooleanField(default=False, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='ra',
            field=models.CharField(blank=True, help_text='RA único de cada aluno', max_length=10, null=True, unique=True, verbose_name='RA'),
        ),
    ]
