# Generated by Django 4.2.13 on 2024-06-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usercustom_is_company_alter_usercustom_ra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='is_company',
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='usercustom',
            name='type',
            field=models.CharField(blank=True, choices=[('student', 'Aluno'), ('teacher', 'Professor'), ('company', 'Empresa')], help_text='Tipo de usuário do sistema', max_length=10, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='ra',
            field=models.CharField(blank=True, help_text='R.A único em caso de aluno', max_length=10, null=True, unique=True, verbose_name='R.A'),
        ),
    ]
