# Generated by Django 4.2.13 on 2024-06-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_usercustom_is_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='type',
            field=models.CharField(choices=[('student', 'Aluno'), ('teacher', 'Professor'), ('company', 'Empresa')], default='student', help_text='Tipo de usuário do sistema', max_length=10, verbose_name='Tipo'),
        ),
    ]
