# Generated by Django 4.2.13 on 2024-06-08 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_remove_collegeclass_students'),
        ('users', '0004_alter_usercustom_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='student_class',
            field=models.ForeignKey(blank=True, help_text='Turma do aluno.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='college.collegeclass', verbose_name='Turma'),
        ),
    ]
