# Generated by Django 4.2.13 on 2024-06-08 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usercustom_comapany_sector_usercustom_company_cnpj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustom',
            old_name='comapany_sector',
            new_name='company_sector',
        ),
    ]
