# Generated by Django 4.2.13 on 2024-06-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_delete_studentinternapplication'),
        ('users', '0007_rename_comapany_sector_usercustom_company_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='student_internship',
            field=models.ManyToManyField(blank=True, help_text='Estágios em que o aluno está participando. Selecione todos os aplicáveis.', related_name='students', to='internship.internship', verbose_name='Estágios'),
        ),
    ]
