# Generated by Django 4.2.13 on 2024-06-01 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Departamento')),
                ('code', models.CharField(help_text='Código único do departamento.', max_length=10, unique=True, verbose_name='Código do Departamento')),
                ('responsible', models.ForeignKey(help_text='Professor responsável pelo departamento.', limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Turma')),
                ('start_date', models.DateField(help_text='Data de início do ano letivo.', verbose_name='Data de Início')),
                ('end_date', models.DateField(help_text='Data de término do ano letivo.', verbose_name='Data de Término')),
                ('department', models.ForeignKey(help_text='Departamento ao qual a turma pertence.', on_delete=django.db.models.deletion.CASCADE, to='college.department', verbose_name='Departamento')),
                ('teachers', models.ManyToManyField(help_text='Professores responsáveis pela turma.', limit_choices_to={'is_teacher': True}, related_name='teaching_classes', to=settings.AUTH_USER_MODEL, verbose_name='Professores')),
            ],
        ),
    ]
