# Generated by Django 4.2.13 on 2024-06-01 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeclass',
            name='students',
            field=models.ManyToManyField(help_text='Alunos matriculados na turma.', limit_choices_to={'is_student': True}, related_name='classes', to=settings.AUTH_USER_MODEL, verbose_name='Alunos'),
        ),
    ]
