# Generated by Django 4.2.13 on 2024-06-06 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college', '0002_collegeclass_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeclass',
            name='students',
            field=models.ManyToManyField(help_text='Alunos matriculados na turma.', limit_choices_to={'type': 'student'}, related_name='classes', to=settings.AUTH_USER_MODEL, verbose_name='Alunos'),
        ),
        migrations.AlterField(
            model_name='collegeclass',
            name='teachers',
            field=models.ManyToManyField(help_text='Professores responsáveis pela turma.', limit_choices_to={'type': 'teacher'}, related_name='teaching_classes', to=settings.AUTH_USER_MODEL, verbose_name='Professores'),
        ),
        migrations.AlterField(
            model_name='department',
            name='responsible',
            field=models.ForeignKey(help_text='Professor responsável pelo departamento.', limit_choices_to={'type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
