# Generated by Django 4.2.13 on 2024-06-08 00:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college', '0003_alter_collegeclass_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeclass',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='Alunos matriculados na turma.', limit_choices_to={'type': 'student'}, related_name='classes', to=settings.AUTH_USER_MODEL, verbose_name='Alunos'),
        ),
    ]
