# Generated by Django 4.2.13 on 2024-06-08 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_alter_collegeclass_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeclass',
            name='students',
        ),
    ]
