# Generated by Django 4.2.13 on 2024-06-16 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('college', '0006_alter_collegeclass_teachers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='Professor responsável pelo departamento.', limit_choices_to={'type': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_department', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
