# Generated by Django 4.2.13 on 2024-06-15 03:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_internship_department_internship_description_and_more'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_pdf',
            field=models.FileField(null=True, upload_to='contracts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='internship',
            field=models.ForeignKey(limit_choices_to={'have_contract': True}, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='internship.internship'),
        ),
    ]
