# Generated by Django 4.2.13 on 2024-06-15 12:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_internship_have_contract_alter_internship_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_contract_contract_pdf_alter_contract_internship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_pdf',
            field=models.FileField(help_text='Contrato do estágio em (apenas PDF).', null=True, upload_to='contracts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='internship',
            field=models.ForeignKey(help_text='Estágio relacionado com o contrato.', limit_choices_to={'have_contract': True}, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='internship.internship', verbose_name='Estágio'),
        ),
        migrations.AlterField(
            model_name='contractsignature',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='documents.contract'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.TimeField(verbose_name='Hora de Início')),
                ('end_hour', models.TimeField(verbose_name='Hora de Término')),
                ('date_report', models.DateField(verbose_name='Data do Relatório')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='internship.internship', verbose_name='Estágio')),
                ('student', models.ForeignKey(limit_choices_to={'type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
            ],
        ),
    ]
