# Generated by Django 4.2.13 on 2024-06-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_contract_contract_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(help_text='Descrição do que foi realizado no estágio.', null=True, verbose_name='Relatório'),
        ),
    ]
