# Generated by Django 4.2.13 on 2024-06-08 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Estágio')),
                ('date_start', models.DateField(help_text='Data de início do estágio.', verbose_name='Data de Início')),
                ('date_end', models.DateField(help_text='Data de término do estágio.', verbose_name='Data de Término')),
                ('company', models.ForeignKey(limit_choices_to={'type': 'company'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
