# Generated by Django 4.2.13 on 2024-06-15 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_alter_collegeclass_teachers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='department',
            field=models.ForeignKey(help_text='Departamento relacionado com o estágio será realizado.', null=True, on_delete=django.db.models.deletion.CASCADE, to='college.department', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='internship',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='company',
            field=models.ForeignKey(help_text='Empresa que está oferecendo o estágio.', limit_choices_to={'type': 'company'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Empresa'),
        ),
    ]
