# Generated by Django 4.2.13 on 2024-06-15 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_alter_collegeclass_teachers_and_more'),
        ('internship', '0002_internship_department_internship_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='have_contract',
            field=models.BooleanField(default=False, verbose_name='Possui Contrato'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='department',
            field=models.ForeignKey(help_text='Departamento relacionado com o estágio que será realizado.', null=True, on_delete=django.db.models.deletion.CASCADE, to='college.department', verbose_name='Departamento'),
        ),
    ]
