# Generated by Django 4.2.13 on 2024-06-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_studentinternapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentInternApplication',
        ),
    ]
