# Generated by Django 4.2.13 on 2024-06-28 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internship', '0005_delete_studentinternapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='company',
            field=models.ForeignKey(help_text='Empresa que está oferecendo o estágio.', limit_choices_to={'type': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='internships', to=settings.AUTH_USER_MODEL, verbose_name='Empresa'),
        ),
    ]
